### ISSUE TITLE
How much of the UCI protocol is implemented?

### ISSUE THREAD

**Issue by jxu** [thomasahle/sunfish#93]
Is it documented anywhere?
I was thinking about writing an engine myself and wondering how I could implement UCI stateless protocol, including `stop` / `go infinite`. I thought I either needed threads or interrupt execution every so often to check if it should stop.

But from uci.py I don't see `stop` or `go infinite` implemented anywhere.

**Comment by tissatussa** [comment]
@jxu hi,

> I was thinking about writing an engine myself

then do not use Python, because it's slow .. i've seen many programmers use Python the create a chess engine, but i guess that's mainly because they know the language and want to try to code SOME chess engine, eg. for learning .. some programmers then switch to C / C++ to rebuild their concept and compile a fast binary.

**Comment by thomasahle** [comment]
@jxu Check the `uci.py` file
