### ISSUE TITLE
about using pypy

### ISSUE THREAD

**Issue by tissatussa** [thomasahle/sunfish#98]
most python3 scripts can be executed with pypy(3) as i understand .. i never had problems with it .. your README states :

> An easy way to get a strong Sunfish is to run with with the PyPy Just-In-Time intepreter.

to me, this makes using pypy an option, but on top of `./sunfish.py` i see this code line :

`#!/usr/bin/env pypy3`

does it mean pypy3 will always be used, even when i do `$ python3 ./sunfish.py` ?
i don't understand - sometimes i even see a script which has no such header code at all .. maybe the extension `.py` is enough for the OS to run it properly ?

**Comment by thomasahle** [comment]
If you run the script with `$ python3 ./sunfish.py` (or `$ python3 sunfish.py`) the header is ignored.
The header is only relevant if you want to run the script with `$ ./sunfish.py`. The later is useful when using sunfish with tools that expect a single executable (like cutechess-cli) rather than a full command with arguments.
